#!/usr/bin/env node
// Convert the harness's Claude Code agent files into OpenCode subagents.
//
// Usage: node convert-agents.mjs <claude-agents-dir> <opencode-agents-dir>
//   Global: <opencode-agents-dir> = ~/.config/opencode/agents
//   Project: <opencode-agents-dir> = <project>/.opencode/agents
//
// Why convert rather than copy: OpenCode validates agent frontmatter and refuses
// to start on a Claude Code file (`tools: Read, Grep` must be an object, `color:
// blue` must be a hex or theme name). Mapping, per opencode.ai/docs/agents:
//   name        -> dropped (the filename is the agent name)
//   description -> kept up to its "Examples:"/<example> block (the examples are Claude Code
//                  routing prompts, and every subagent description sits in every
//                  OpenCode prompt); harness:-qualified names become bare
//   model       -> dropped: the subagent inherits the session's model, which is
//                  what lets the same file run on a local model
//   color       -> dropped
//   tools       -> permission: no Edit/Write -> edit deny; Bash(git:*) -> bash
//                  {"*": deny, "git *": allow}; no Bash -> bash deny; no
//                  WebFetch/WebSearch/Task -> webfetch/websearch/task deny.
//                  No tools line at all -> no permission block (inherits).
//   body        -> kept; harness:-qualified names become bare
//
// The three graph agents are skipped: they exist to be dispatched by the
// plan-graph/review-graph workflow scripts, which OpenCode cannot run.
//
// A generated file carries MARK. Re-running overwrites generated files and never
// touches a same-named file without MARK (a user's own agent).
import fs from 'node:fs'
import path from 'node:path'

const GRAPH_AGENTS = new Set(['plan-investigator', 'claim-refuter', 'finding-refuter'])
const MARK = '# generated by agent-harness-config opencode/convert-agents.mjs - edits are overwritten'

const [src, dest] = process.argv.slice(2)
if (!src || !dest) {
  console.error('usage: convert-agents.mjs <claude-agents-dir> <opencode-agents-dir>')
  process.exit(2)
}

function parseFrontmatter(text) {
  const lines = text.split('\n')
  if (lines[0] !== '---') throw new Error('no frontmatter')
  const end = lines.indexOf('---', 1)
  if (end < 0) throw new Error('unterminated frontmatter')
  const fields = {}
  for (const line of lines.slice(1, end)) {
    const m = line.match(/^([A-Za-z_-]+):\s*(.*)$/)
    if (!m) continue
    let value = m[2].trim()
    if (value.startsWith('"')) {
      try { value = JSON.parse(value) } catch { value = value.replace(/^"|"$/g, '') }
    }
    fields[m[1]] = value.replace(/\\n/g, '\n')
  }
  return { fields, body: lines.slice(end + 1).join('\n') }
}

const unqualify = s => s.replace(/harness:([a-z0-9-]+)/g, '$1')

function toPermission(tools) {
  if (tools === undefined || tools.trim() === '') return null
  const list = tools.split(',').map(t => t.trim()).filter(Boolean)
  const has = name => list.includes(name)
  const perm = {}
  if (!['Edit', 'Write', 'MultiEdit', 'NotebookEdit'].some(has)) perm.edit = 'deny'
  if (!has('Bash')) {
    const patterns = list
      .map(t => t.match(/^Bash\((.*)\)$/))
      .filter(Boolean)
      .map(m => m[1].split(':').join(' '))
    perm.bash = patterns.length
      ? Object.fromEntries([['*', 'deny'], ...patterns.map(p => [p, 'allow'])])
      : 'deny'
  }
  if (!has('WebFetch')) perm.webfetch = 'deny'
  if (!has('WebSearch')) perm.websearch = 'deny'
  if (!has('Task') && !has('Agent')) perm.task = 'deny'
  return perm
}

function convert(text) {
  const { fields, body } = parseFrontmatter(text)
  const description = unqualify((fields.description || '').split(/\s*Examples?:|<example>/)[0])
    .replace(/\s+/g, ' ')
    .trim()
  const out = ['---', MARK, `description: ${JSON.stringify(description)}`, 'mode: subagent']
  const perm = toPermission(fields.tools)
  if (perm) {
    out.push('permission:')
    for (const [key, value] of Object.entries(perm)) {
      if (typeof value === 'string') { out.push(`  ${key}: ${value}`); continue }
      out.push(`  ${key}:`)
      for (const [pattern, action] of Object.entries(value)) out.push(`    ${JSON.stringify(pattern)}: ${action}`)
    }
  }
  out.push('---')
  return { name: fields.name, text: out.join('\n') + '\n' + unqualify(body) }
}

fs.mkdirSync(dest, { recursive: true })
let converted = 0
for (const file of fs.readdirSync(src).filter(f => f.endsWith('.md')).sort()) {
  const { name, text } = convert(fs.readFileSync(path.join(src, file), 'utf8'))
  const agent = name || path.basename(file, '.md')
  if (GRAPH_AGENTS.has(agent)) continue
  const target = path.join(dest, `${agent}.md`)
  if (fs.existsSync(target) && !fs.readFileSync(target, 'utf8').includes(MARK)) {
    console.log(`  exists, not generated by the harness - skipped: ${target}`)
    continue
  }
  fs.writeFileSync(target, text)
  converted++
}
console.log(`agents converted: ${converted} (at ${dest})`)
